version: '3'

services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: This1sPassw0r4
      MYSQL_DATABASE: db_test001
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
